dataset: 'shuttle'
model:
  name: 'ae'
  nr_enc_lyrs: 3
  hidden_sizes:
    - 7
    - 3
    - 2
  optimizer: 'Adam'
  loss: 'L1Loss'
  lr: 0.01
  anomaly_trhold: 0.9
dev: 'cuda:0'
nr_models: 3
batch_size: 64
local_epochs: 2
rounds: 5
val_metric: 'auc'

