dataset: 'shuttle'
model:
  name: 'gan'
  optimizer: 'SGD'
  loss: 'BCE'
  gen_lr: 0.0004
  disc_lr: 0.0001
  momentum: 0.9
  dampening: 0.000001
  anomaly_trhold: 0.92851
  data_size: 64
dev: 'cuda:0'
nr_models: 3
batch_size: 64
local_epochs: 2
rounds: 2
val_metric: 'accuracy'