dataset: 'shuttle'
model:
  name: 'ae'
  nr_enc_lyrs: 1
  hidden_sizes:
    - 5
  optimizer: 'Adam'
  loss: 'MSELoss'
  lr: 0.02
  anomaly_trhold: 0.92851
dev: 'cuda:0'
nr_models: 3
batch_size: 64
local_epochs: 2
rounds: 2
val_metric: 'accuracy'

